spring:
  # DB ??
  datasource:
    # ??? H2 DB? ?? URL
    url: jdbc:h2:tcp://localhost/~/restaurantDapp
    # ??? ?? ????
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    # JPA? ???? SQL? ? ? ??.
    show-sql: true
    # ??? ?? ???? ??? ?? ??. ?? - create, ??? - none
    # ????? ??? create? ????
    # ???? none ?? ???. create?? ??? ???? ?? ??????.
    hibernate:
      ddl-auto: create

  # ?? ?? ? ?? always
  output:
    ansi:
      enabled: always
# ???? ??? ?? trace
logging:
  level:
    org.hibernate.sql: debug